# Build and deploy the GitHub Pages site
# This workflow is triggered on push events to the main branch.
# It builds the site and deploys it to GitHub Pages.
# The workflow has write permissions to the GitHub Pages site
# and the Actions token is available in the workflow.
# @author Rhea Mimi Carillo @RheaMimiCarillo <https://github.com/RheaMimiCarillo>
# author UWT Game Dev Club @uwtgdc <https://github.com/uwtgdc>
# @version 21 October 2025
#

name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout the repo
      - uses: actions/setup-node@v4 # Set up Node.js
        with:
          node-version: '20' # Use Node.js version 20
      - run: npm ci || npm i # Install dependencies
      - run: npm run build # Build the site
      - uses: actions/upload-pages-artifact@v3 # Upload the built site
        with:
          path: dist # Upload the contents of the dist directory
  deploy:
    needs: build # Requires successful build job before deploying
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Set the environment variable GITHUB_PAGES_URL to the URL of the deployed site
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4 # Deploy the site to GitHub Pages
